name: Deploy to AWS Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: SSH into the AWS server and execute commands
    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_SERVER_IP }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Step 3: Navigate to the target folder
          cd book-management-system-backend/
          
          # checkout to the correct branch and pull the latest changes
          git checkout main 
          git pull
          
          # Step 6: Set up Python virtual environment
          source venv/bin/activate

          # Step 8: Install dependencies (if any)
          pip install -r requirements.txt

          # Step 9: Run the Python script
          python main.py
